AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: qatar scanner bot

Globals:
  Function:
    Timeout: 5
    MemorySize: 128

Resources:
  QatarScannerFunction:
    Type: AWS::Serverless::Function
    Properties:
      PackageType: Image
      Architectures:
        - x86_64
      Policies:
        - SSMParameterReadPolicy:
            ParameterName: 'applications-db'
        - SQSSendMessagePolicy:
            QueueName: !ImportValue TelegramMessageQueueName
      Environment:
        Variables:
          SQS_QUEUE_URL: !ImportValue TelegramMessageQueueUrl
          ENVIRONMENT: prod
      Events:
        QatarScannerSchedule:
          Type: Schedule
          Properties:
            Schedule: 'rate(1 minute)'
            Name: QatarScannerSchedule
            Description: Qatar scanner schedule
            Enabled: true
    Metadata:
      DockerTag: nodejs14.x-v1
      DockerContext: ./
      Dockerfile: Dockerfile
